//
//  LocationAnnotation.swift
//  SerenityStops
//
//  Created by Ayush Kumar Singh on 17/12/24.
//

import Foundation

import MapKit

/// A model representing a location-based annotation with associated emotional sentiment.
///
/// This struct conforms to `Identifiable` and represents a point of interest on the map
/// where users have recorded their emotional experiences.
///
/// - Important: Coordinates must be valid geographic coordinates.
/// - Note: Each annotation is uniquely identified and includes creation timestamp.

struct LocationAnnotation: Identifiable {
    
    /// Unique identifier for the annotation.
    ///
    /// This ID is automatically generated during initialization and
    /// used for uniquely identifying annotations in collections.
    let id: UUID
    
    /// The geographic coordinates of the annotation.
    ///
    /// - Important: Coordinates should be within valid ranges:
    ///   - Latitude: -90.0 to 90.0
    ///   - Longitude: -180.0 to 180.0
    let coordinate: CLLocationCoordinate2D
    
    /// The emotional sentiment label associated with this location.
    ///
    /// This label is typically generated by the `Analyzer` class and includes
    /// both emoji and text description of the emotional state.
    let label: String
    
    /// The timestamp when this annotation was created.
    let createdAt: Date
    
    init(coordinate: CLLocationCoordinate2D, label: String, createdAt: Date = Date()) {
        precondition(CLLocationCoordinate2DIsValid(coordinate),
                     "Invalid coordinate provided: \(coordinate)")
        
        self.id = UUID()
        self.coordinate = coordinate
        self.label = label
        self.createdAt = createdAt
    }
}

extension LocationAnnotation: CustomStringConvertible {
    /// A textual representation of the annotation.
    var description: String {
        "Location(\(coordinate.latitude), \(coordinate.longitude)) - \(label)"
    }
}
